export const PROJECTS = [
  [
    {
      title: "CampusCare – Your Student Wellness Partner",
      desc: "A mobile-first guidance counseling platform built using Flutter and Firebase, designed to help students book appointments, chat with counselors, and access wellness tools.",
      img: "/images/project1.png",
      alt: "CampusCare - Student wellness platform screenshot",
      link: "https://github.com/yourusername/campuscare",
      demoLink: "https://campuscare-demo.com",
      techStack: [
        "Flutter",
        "Firebase",
        "Dart",
        "Cloud Firestore",
        "Firebase Auth",
      ],
      category: "Mobile Application",
      members: ["Ken Developer", "UI/UX Designer"],
      features: [
        "Real-time chat",
        "Appointment booking",
        "Wellness tracking",
        "Push notifications",
      ],
      duration: "3 months",
      status: "Completed",
    },
    {
      title: "Hotel Booking & Reservation System",
      desc: "A robust hotel booking platform with real-time availability and secure payments.",
      img: "/images/project2.png",
      alt: "Hotel reservation system interface",
      link: "https://github.com/yourusername/hotel-booking",
      demoLink: "https://hotel-booking-demo.com",
      techStack: ["React", "Node.js", "MongoDB", "Express", "Stripe API"],
      category: "Web Application",
      members: ["Ken Developer", "Backend Developer"],
      features: [
        "Real-time booking",
        "Payment integration",
        "Admin dashboard",
        "Email notifications",
      ],
      duration: "4 months",
      status: "Completed",
    },
    {
      title: "CampusCare Admin Dashboard",
      desc: "Admin dashboard for managing appointments, counselors, and analytics.",
      img: "/images/project33.png",
      alt: "Admin dashboard with analytics and management tools",
      link: "https://github.com/yourusername/campuscare-admin",
      demoLink: "https://campuscare-admin-demo.com",
      techStack: ["React", "Material-UI", "Firebase", "Chart.js"],
      category: "Web Dashboard",
      members: ["Ken Developer"],
      features: [
        "Analytics dashboard",
        "User management",
        "Appointment tracking",
        "Reports",
      ],
      duration: "2 months",
      status: "Completed",
    },
  ],
  [
    {
      title: "Pacebeats Landing Page",
      desc: "Modern running app showcase built with Astro and TailwindCSS, featuring heart rate monitoring and pace tracking for runners with Samsung Health SDK integration.",
      img: "/images/projects/project2/1.jpg",
      alt: "Pacebeats landing page - Modern running app showcase",
      link: "https://github.com/KpG782/Pacebeats-landing-page",
      demoLink: "https://pacebeats.top",
      techStack: ["Astro", "TailwindCSS", "TypeScript"],
      category: "Landing Page",
      members: [
        "Ken Patrick Garcia",
        "Timothy Forte",
        "Brian Ashley Papa",
        "Lanz Corpuz",
      ],
      features: [
        "Responsive design",
        "Interactive sections",
        "Fast performance",
        "Conversion focused CTAs",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "Designers' Cafe Website",
      desc: "Digital showcase for a creative coffee shop in Pembo, Taguig, featuring interactive menu, gallery, and community-focused design atmosphere.",
      img: "/images/projects/project2/2.png",
      alt: "Designers' Cafe website interface",
      link: "https://github.com/KpG782/designers-cafe",
      demoLink: "https://designers-cafe.vercel.app",
      techStack: ["Astro", "TailwindCSS", "JavaScript", "Google Maps API"],
      category: "Business Website",
      members: ["Ken Patrick Garcia"],
      features: [
        "Interactive menu system",
        "3D barista profiles",
        "Contact integration",
        "Responsive gallery",
      ],
      duration: "1.5 months",
      status: "Delivered",
    },
    {
      title: "Tugang Cafe Website",
      desc: "Premium coffee shop website with custom cursor animations, ultrawide support, and engaging scroll animations showcasing togetherness and community.",
      img: "/images/projects/project2/3.png",
      alt: "Tugang Cafe website with coffee-themed design",
      link: "https://github.com/KpG782/tugang-cafe",
      demoLink: "https://tugang-cafe.vercel.app",
      techStack: [
        "Astro",
        "TailwindCSS",
        "Intersection Observer",
        "Custom CSS",
      ],
      category: "Business Website",
      members: ["Ken Patrick Garcia"],
      features: [
        "Custom coffee cursor",
        "Scroll animations",
        "Interactive menu modals",
        "Ultrawide screen support",
      ],
      duration: "1 month",
      status: "Delivered",
    },
    {
      title: "Wedding Template Collection 2",
      desc: "Modern, elegant, and accessible wedding website templates featuring countdown timers, RSVP integration, and beautiful storytelling animations.",
      img: "/images/projects/project2/5.png",
      alt: "Wedding template with elegant design and animations",
      link: "https://github.com/KpG782/WeddingTemplate1",
      demoLink: "https://wedding-template2-one.vercel.app",
      techStack: ["HTML5", "TailwindCSS", "Animate.css", "JavaScript"],
      category: "Template Design",
      members: ["Ken Patrick Garcia", "Aby Ann Avinante"],
      features: [
        "Interactive countdown",
        "RSVP integration",
        "Spotify playlist embed",
        "QR code gift registry",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
    {
      title: "JASM Printing Services",
      desc: "Business website for local printing services in Pasig, showcasing apparel printing, ID cards, labels, and event giveaways with responsive design.",
      img: "/images/projects/project2/6.png",
      alt: "JASM Printing Services business website",
      link: "https://github.com/KpG782/JASMPrinting",
      demoLink: "https://jasm-printing.vercel.app",
      techStack: ["HTML5", "CSS3", "JavaScript", "Font Awesome"],
      category: "Business Website",
      members: [
        "Timothy Forte",
        "Ken Garcia",
        "Lanz Corpuz",
        "Mars Maguddayao",
        "Brian Ashley",
      ],
      features: [
        "Product catalog",
        "Contact forms",
        "Service showcase",
        "Mobile-first design",
      ],
      duration: "6 weeks",
      status: "Delivered",
    },
    {
      title: "Hungry Potter's Tapsilogan",
      desc: "Student-friendly silog restaurant website with responsive menu display, built with Bootstrap 5 and modern CSS for local Filipino dining.",
      img: "/images/projects/project2/7.png",
      alt: "Hungry Potter's restaurant website interface",
      link: "https://github.com/KpG782/HungryPotters",
      demoLink: "https://hungry-potters.vercel.app",
      techStack: ["HTML5", "Bootstrap 5", "CSS3", "JavaScript"],
      category: "Restaurant Website",
      members: [
        "Ken Patrick Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Ejay Buscato",
      ],
      features: [
        "Responsive menu",
        "Bootstrap components",
        "Image carousel",
        "Contact integration",
      ],
      duration: "4 weeks",
      status: "Completed",
    },
    {
      title: "Wedding Template Collection 1",
      desc: "Modern, elegant, and accessible wedding website templates featuring countdown timers, RSVP integration, and beautiful storytelling animations.",
      img: "/images/projects/project2/4.png",
      alt: "Wedding template with elegant design and animations",
      link: "https://github.com/KpG782/WeddingTemplate1",
      demoLink: "https://wedding-template2-one.vercel.app",
      techStack: ["HTML5", "TailwindCSS", "Animate.css", "JavaScript"],
      category: "Template Design",
      members: ["Ken Patrick Garcia", "Aby Ann Avinante"],
      features: [
        "Interactive countdown",
        "RSVP integration",
        "Spotify playlist embed",
        "QR code gift registry",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
  ],
  [
    {
      title: "Responsive Landing Page",
      desc: "Frontend challenge: pixel-perfect landing page with animations.",
      img: "/images/challenge1.png",
      alt: "Responsive landing page with animations",
      link: "https://github.com/yourusername/responsive-landing",
      demoLink: "https://responsive-landing-demo.com",
      techStack: ["HTML5", "CSS3", "JavaScript", "GSAP"],
      category: "Frontend Challenge",
      members: ["Ken Developer"],
      features: [
        "Responsive design",
        "CSS animations",
        "Performance optimized",
        "Cross-browser compatible",
      ],
      duration: "1 week",
      status: "Completed",
    },
    {
      title: "Dashboard UI",
      desc: "Frontend challenge: dashboard with charts and filters.",
      img: "/images/challenge2.png",
      alt: "Interactive dashboard with charts and data visualization",
      link: "https://github.com/yourusername/dashboard-ui",
      demoLink: "https://dashboard-ui-demo.com",
      techStack: ["React", "D3.js", "Styled Components", "TypeScript"],
      category: "UI/UX Design",
      members: ["Ken Developer"],
      features: [
        "Interactive charts",
        "Data filtering",
        "Dark/Light theme",
        "Export functionality",
      ],
      duration: "2 weeks",
      status: "Completed",
    },
  ],
  [
    {
      title: "Weather App",
      desc: "Simple weather app using OpenWeather API.",
      img: "/images/other1.png",
      alt: "Weather application showing current conditions",
      link: "https://github.com/yourusername/weather-app",
      demoLink: "https://weather-app-demo.com",
      techStack: ["JavaScript", "OpenWeather API", "CSS3", "HTML5"],
      category: "Utility App",
      members: ["Ken Developer"],
      features: [
        "Current weather",
        "5-day forecast",
        "Location search",
        "Weather maps",
      ],
      duration: "3 days",
      status: "Completed",
    },
    {
      title: "Markdown Editor",
      desc: "Live markdown editor built with React.",
      img: "/images/other2.png",
      alt: "Live markdown editor with preview functionality",
      link: "https://github.com/yourusername/markdown-editor",
      demoLink: "https://markdown-editor-demo.com",
      techStack: ["React", "CodeMirror", "Marked.js", "CSS3"],
      category: "Text Editor",
      members: ["Ken Developer"],
      features: [
        "Live preview",
        "Syntax highlighting",
        "Export to HTML",
        "Local storage",
      ],
      duration: "1 week",
      status: "Completed",
    },
  ],
];
