export const PROJECTS = [
  // Tab 0: Full Stack Applications & Websites
  [
    {
      title: "Pacebeats – Smart Heart Rate Monitoring for Runners",
      desc: "A modern Android application built with Kotlin and Jetpack Compose that provides real-time heart rate monitoring and pace tracking for runners. Seamlessly integrated with Samsung Health SDK, PaceBeats transforms your Galaxy Watch into a powerful fitness companion.",
      img: "/images/projects/project1/1.jpg",
      alt: "Pacebeats - Smart heart rate monitoring app interface",
      link: "https://github.com/KpG782",
      demoLink: "https://pacebeats.top",
      techStack: [
        "Kotlin",
        "Jetpack Compose",
        "Samsung Health SDK",
        "Android Studio",
        "MVVM Architecture",
      ],
      category: "Mobile Application",
      members: [
        "Ken Patrick Garcia",
        "Timothy Forte",
        "Brian Ashley Papa",
        "Lanz Corpuz",
      ],
      features: [
        "Real-time heart rate monitoring",
        "Inter-beat interval analysis",
        "Smart pace detection",
        "Galaxy Watch integration",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
    {
      title: "CampusCare – Student Wellness Platform",
      desc: "A comprehensive mobile-first guidance counseling platform built using Flutter and Firebase, designed to help University of Makati students book appointments, chat with counselors, and access wellness tools with AI-powered mood analysis.",
      img: "/images/projects/project1/2.png",
      alt: "CampusCare - Student wellness platform screenshot",
      link: "https://github.com/KpG782/CampusCare",
      demoLink:
        "https://drive.google.com/drive/folders/1RcX2Sduq-87-wtzQmxIjrcNhyXWUNMeN?usp=sharing",
      techStack: [
        "Flutter",
        "Firebase",
        "Dart",
        "Cloud Firestore",
        "DistilBERT AI",
      ],
      category: "Mobile Application",
      members: [
        "Ken Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Brian Ashley",
      ],
      features: [
        "AI-powered mood analysis using DistilBERT",
        "Real-time chat with counselors",
        "Appointment booking system",
        "Secure authentication and user management",
      ],
      duration: "3 months",
      status: "Completed",
    },
    {
      title: "CampusCare Admin Dashboard",
      desc: "A robust admin platform for managing CampusCare's guidance counseling services. Built with FlutterFlow and Flutter, it empowers admins and counselors to manage student well-being, appointments, and analytics.",
      img: "/images/projects/project1/5.png",
      alt: "CampusCare Admin dashboard with analytics and management tools",
      link: "https://github.com/KpG782/CampusCareAdmin",
      demoLink: "https://campuscareadmin.flutterflow.app/",
      techStack: ["Flutter", "FlutterFlow", "Firebase", "Cloud Functions"],
      category: "Web Dashboard",
      members: ["Ken Garcia", "Timothy Forte", "Lanz Corpuz"],
      features: [
        "Session management system",
        "Analytics & reports dashboard",
        "Counselor profile management",
        "Push notifications",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "MovieFlix – React Native Movie Browser",
      desc: "A beautiful movie browsing app built with React Native and Expo. Demonstrates fetching and displaying data from The Movie Database (TMDB) API with smooth navigation and responsive UI.",
      img: "/images/projects/project1/3.png",
      alt: "MovieFlix React Native app interface",
      link: "https://github.com/KpG782/MovieFlix-React",
      demoLink: "#",
      techStack: [
        "React Native",
        "Expo",
        "TMDB API",
        "AsyncStorage",
        "React Navigation",
      ],
      category: "Mobile Application",
      members: ["Ken Patrick Garcia"],
      features: [
        "TMDB API integration",
        "Movie search functionality",
        "Local favorites storage",
        "Cross-platform compatibility",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
    {
      title: "3D Developer Portfolio",
      desc: "A modern and interactive 3D web developer portfolio built with React, Vite, Three.js, and GSAP. Features real-time 3D animations and scroll-based interactions for an immersive user experience.",
      img: "/images/projects/project1/4.png",
      alt: "3D Developer Portfolio with Three.js animations",
      link: "https://github.com/KpG782/3D_Portfolio",
      demoLink: "https://3-d-portfolio-eight-pi.vercel.app",
      techStack: ["React", "Vite", "Three.js", "GSAP", "React Three Fiber"],
      category: "Web Application",
      members: ["Ken Patrick Garcia"],
      features: [
        "Real-time 3D animations",
        "Scroll-based GSAP animations",
        "Responsive 3D design",
        "Interactive UI components",
      ],
      duration: "1 month",
      status: "Completed",
    },
    {
      title: "SeqSense – Mathematical Sequences Visualizer",
      desc: "A Flutter application for visualizing and experimenting with popular number sequences and mathematical algorithms. Features interactive calculators for Fibonacci, Lucas, Tribonacci, Collatz, Pascal's Triangle, and Euclidean GCD.",
      img: "/images/projects/project1/6.png",
      alt: "SeqSense mathematical sequences visualization app",
      link: "https://github.com/KpG782/SeqSense",
      demoLink: "#",
      techStack: ["Flutter", "Dart", "FlutterFlow", "Custom Algorithms"],
      category: "Educational App",
      members: ["Ken Patrick Garcia", "Brian Ashley Papa", "Mars Maguddayao"],
      features: [
        "Interactive sequence calculators",
        "Real-time result visualization",
        "Multiple mathematical algorithms",
        "Educational interface design",
      ],
      duration: "1.5 months",
      status: "Completed",
    },
  ],
  // Tab 1: Sample Full Stack Design for Clients
  [
    {
      title: "Pacebeats Landing Page",
      desc: "Modern running app showcase built with Astro and TailwindCSS, featuring heart rate monitoring and pace tracking for runners with Samsung Health SDK integration.",
      img: "/images/projects/project2/1.jpg",
      alt: "Pacebeats landing page - Modern running app showcase",
      link: "https://github.com/KpG782/Pacebeats-landing-page",
      demoLink: "https://pacebeats.top",
      techStack: ["Astro", "TailwindCSS", "TypeScript"],
      category: "Landing Page",
      members: [
        "Ken Patrick Garcia",
        "Timothy Forte",
        "Brian Ashley Papa",
        "Lanz Corpuz",
      ],
      features: [
        "Responsive design",
        "Interactive sections",
        "Fast performance with Astro SSG",
        "Conversion focused CTAs",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "Designers' Cafe Website",
      desc: "Digital showcase for a creative coffee shop in Pembo, Taguig, featuring interactive menu, gallery, and community-focused design atmosphere.",
      img: "/images/projects/project2/2.png",
      alt: "Designers' Cafe website interface",
      link: "https://github.com/KpG782/designers-cafe",
      demoLink: "https://designers-cafe.vercel.app",
      techStack: ["Astro", "TailwindCSS", "JavaScript", "Google Maps API"],
      category: "Business Website",
      members: ["Ken Patrick Garcia"],
      features: [
        "Interactive menu system",
        "3D barista profiles",
        "Google Maps integration",
        "Responsive gallery",
      ],
      duration: "1.5 months",
      status: "Delivered",
    },
    {
      title: "Tugang Cafe Website",
      desc: "Premium coffee shop website with custom cursor animations, ultrawide support, and engaging scroll animations showcasing togetherness and community.",
      img: "/images/projects/project2/3.png",
      alt: "Tugang Cafe website with coffee-themed design",
      link: "https://github.com/KpG782/tugang-cafe",
      demoLink: "https://tugang-cafe.vercel.app",
      techStack: [
        "Astro",
        "TailwindCSS",
        "Intersection Observer",
        "Custom CSS",
      ],
      category: "Business Website",
      members: ["Ken Patrick Garcia"],
      features: [
        "Custom coffee cursor animation",
        "Scroll animations with Intersection Observer",
        "Interactive menu modals",
        "Ultrawide screen support",
      ],
      duration: "1 month",
      status: "Delivered",
    },
    {
      title: "Wedding Template Collection 1",
      desc: "Modern, elegant, and accessible wedding website templates featuring countdown timers, RSVP integration, and beautiful storytelling animations.",
      img: "/images/projects/project2/4.png",
      alt: "Wedding template with elegant design and animations",
      link: "https://github.com/KpG782/WeddingTemplate1",
      demoLink: "https://wedding-template2-one.vercel.app",
      techStack: ["HTML5", "TailwindCSS", "Animate.css", "JavaScript"],
      category: "Template Design",
      members: ["Ken Patrick Garcia", "Aby Ann Avinante"],
      features: [
        "Interactive countdown timer",
        "RSVP form integration",
        "Spotify playlist embed",
        "QR code gift registry",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
    {
      title: "Wedding Template Collection 2",
      desc: "Modern, elegant, and accessible wedding website templates featuring countdown timers, RSVP integration, and beautiful storytelling animations.",
      img: "/images/projects/project2/5.png",
      alt: "Wedding template with elegant design and animations",
      link: "https://github.com/KpG782/WeddingTemplate1",
      demoLink: "https://wedding-template2-one.vercel.app",
      techStack: ["HTML5", "TailwindCSS", "Animate.css", "JavaScript"],
      category: "Template Design",
      members: ["Ken Patrick Garcia", "Aby Ann Avinante"],
      features: [
        "Interactive countdown timer",
        "RSVP form integration",
        "Spotify playlist embed",
        "QR code gift registry",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
    {
      title: "JASM Printing Services",
      desc: "Business website for local printing services in Pasig, showcasing apparel printing, ID cards, labels, and event giveaways with responsive design.",
      img: "/images/projects/project2/6.png",
      alt: "JASM Printing Services business website",
      link: "https://github.com/KpG782/JASMPrinting",
      demoLink: "https://jasm-printing.vercel.app",
      techStack: ["HTML5", "CSS3", "JavaScript", "Font Awesome"],
      category: "Business Website",
      members: [
        "Timothy Forte",
        "Ken Garcia",
        "Lanz Corpuz",
        "Mars Maguddayao",
        "Brian Ashley",
      ],
      features: [
        "Product catalog showcase",
        "Contact forms",
        "Service showcase sections",
        "Mobile-first design approach",
      ],
      duration: "6 weeks",
      status: "Delivered",
    },
    {
      title: "Hungry Potter's Tapsilogan",
      desc: "Student-friendly silog restaurant website with responsive menu display, built with Bootstrap 5 and modern CSS for local Filipino dining.",
      img: "/images/projects/project2/7.png",
      alt: "Hungry Potter's restaurant website interface",
      link: "https://github.com/KpG782/HungryPotters",
      demoLink: "https://hungry-potters.vercel.app",
      techStack: ["HTML5", "Bootstrap 5", "CSS3", "JavaScript"],
      category: "Restaurant Website",
      members: [
        "Ken Patrick Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Ejay Buscato",
      ],
      features: [
        "Responsive menu display",
        "Bootstrap 5 components",
        "Image carousel for dishes",
        "Contact information integration",
      ],
      duration: "4 weeks",
      status: "Completed",
    },
  ],
  // Tab 2: Frontend Development
  [
    {
      title: "Interactive Portfolio with Three.js",
      desc: "Showcase of advanced frontend skills with 3D graphics, animations, and modern web technologies. Features immersive 3D scenes and smooth scroll-based interactions.",
      img: "/images/projects/project1/4.png",
      alt: "Interactive 3D portfolio website",
      link: "https://github.com/KpG782/3D_Portfolio",
      demoLink: "https://3-d-portfolio-eight-pi.vercel.app",
      techStack: ["React", "Three.js", "GSAP", "Vite", "TailwindCSS"],
      category: "Frontend Showcase",
      members: ["Ken Patrick Garcia"],
      features: [
        "3D scene rendering with Three.js",
        "GSAP scroll animations",
        "Responsive 3D design",
        "Performance optimized",
      ],
      duration: "1 month",
      status: "Completed",
    },
    {
      title: "Responsive Landing Page Design",
      desc: "Modern landing page built with cutting-edge frontend technologies, featuring smooth animations, micro-interactions, and pixel-perfect responsive design.",
      img: "/images/projects/project2/1.jpg",
      alt: "Responsive landing page with modern design",
      link: "https://github.com/KpG782/Pacebeats-landing-page",
      demoLink: "https://pacebeats.top",
      techStack: ["Astro", "TailwindCSS", "TypeScript", "CSS Grid"],
      category: "Frontend Challenge",
      members: ["Ken Patrick Garcia"],
      features: [
        "Mobile-first responsive design",
        "CSS Grid and Flexbox layouts",
        "Optimized performance",
        "Accessible UI components",
      ],
      duration: "2 weeks",
      status: "Completed",
    },
    {
      title: "Modern UI Components Library",
      desc: "Collection of reusable UI components built with modern CSS and JavaScript, featuring animations, transitions, and interactive elements.",
      img: "/images/projects/project2/2.png",
      alt: "UI components library showcase",
      link: "https://github.com/KpG782/designers-cafe",
      demoLink: "https://designers-cafe.vercel.app",
      techStack: ["HTML5", "CSS3", "JavaScript", "TailwindCSS"],
      category: "UI/UX Design",
      members: ["Ken Patrick Garcia"],
      features: [
        "Reusable component system",
        "Smooth CSS transitions",
        "Interactive hover effects",
        "Cross-browser compatible",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
  ],
  // Tab 3: Other Projects
  [
    {
      title: "Mathematical Algorithms Visualizer",
      desc: "Educational tool for visualizing mathematical sequences and algorithms. Built with Flutter to demonstrate complex mathematical concepts in an interactive way.",
      img: "/images/projects/project1/6.png",
      alt: "Mathematical algorithms visualization",
      link: "https://github.com/KpG782/SeqSense",
      demoLink: "#",
      techStack: ["Flutter", "Dart", "Custom Algorithms"],
      category: "Educational Tool",
      members: ["Ken Patrick Garcia", "Brian Ashley Papa", "Mars Maguddayao"],
      features: [
        "Fibonacci sequence calculator",
        "Lucas numbers visualization",
        "Collatz conjecture explorer",
        "Pascal's triangle generator",
      ],
      duration: "1.5 months",
      status: "Completed",
    },
    {
      title: "Movie Database Browser",
      desc: "Cross-platform movie browsing application demonstrating API integration and mobile development skills with React Native.",
      img: "/images/projects/project1/3.png",
      alt: "Movie database browser app",
      link: "https://github.com/KpG782/MovieFlix-React",
      demoLink: "#",
      techStack: ["React Native", "Expo", "TMDB API", "AsyncStorage"],
      category: "Utility App",
      members: ["Ken Patrick Garcia"],
      features: [
        "TMDB API integration",
        "Search and filter movies",
        "Save favorite movies",
        "Cross-platform support (iOS & Android)",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
    {
      title: "Custom Cursor & Animation Library",
      desc: "Collection of custom cursors and micro-animations for web projects, demonstrating advanced CSS and JavaScript animation techniques.",
      img: "/images/projects/project2/3.png",
      alt: "Custom cursor animations showcase",
      link: "https://github.com/KpG782/tugang-cafe",
      demoLink: "https://tugang-cafe.vercel.app",
      techStack: ["JavaScript", "CSS3", "Intersection Observer API"],
      category: "Animation Library",
      members: ["Ken Patrick Garcia"],
      features: [
        "Custom cursor animations",
        "Scroll-triggered effects",
        "Intersection Observer implementation",
        "Performance optimized animations",
      ],
      duration: "2 weeks",
      status: "Completed",
    },
    {
      title: "Bootstrap Component Showcase",
      desc: "Demonstration of Bootstrap 5 capabilities through a complete restaurant website, showcasing responsive components and modern layout techniques.",
      img: "/images/projects/project2/7.png",
      alt: "Bootstrap components showcase",
      link: "https://github.com/KpG782/HungryPotters",
      demoLink: "https://hungry-potters.vercel.app",
      techStack: ["Bootstrap 5", "HTML5", "CSS3", "JavaScript"],
      category: "Framework Demo",
      members: [
        "Ken Patrick Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Ejay Buscato",
      ],
      features: [
        "Bootstrap 5 grid system",
        "Responsive navigation",
        "Card components",
        "Modal implementations",
      ],
      duration: "4 weeks",
      status: "Completed",
    },
  ],
];
